import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TheHeader } from './Components/TheHeader';
import { TheFooter } from './Components/TheFooter';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TheHeader />
        <main className="container">
          {children}
        </main>
        <TheFooter />
        </body>
    </html>
  )
}
