
import './globals.css';
import type { Metadata } from 'next';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { Filter } from '../components/Filter';
import  ProductCard  from '../components/ProductCard';
import "./globals.css";
import localFont from 'next/font/local';
import styles from '../app/page.module.css'
 

const Satoshi = localFont({ src: '../public/fonts/Satoshi_Complete/Satoshi-Medium.woff2' });
 

export const metadata: Metadata = {
  title: 'Next App2',
  description: 'Generated by next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Satoshi.className}>
        <Header />
        
        <section className={styles.main}> 
           <Filter />
              <div className={styles.cards}>
                  <ProductCard />
                  <ProductCard />
                  <ProductCard />
                  <ProductCard />
                  <ProductCard />
                  <ProductCard />
                  
              </div>
        </section>
         
       
        <Footer />
        </body>
    </html>
  );
}
